spring:
  profiles: postgres
  jpa:
   database: POSTGRESQL
  datasource:
   url: jdbc:postgresql://localhost:5432/entity_image
   username: postgres
   password: postgres
   platform: postgres
  database:
   driverClassName: org.postgresql.Driver


