---
spring:
  profiles: h2
  h2:
   console:
    enabled: true
    path: /h2
  datasource:
   url: jdbc:h2:file:~/test
   username: sa
   password:
   driver-class-name: org.h2.Driver
liquibase:
   contexts: h2
---
spring:
  profiles: postgres
  jpa:
   database: POSTGRESQL
  datasource:
   url: jdbc:postgresql://localhost:5432/entity_image
   username: postgres
   password: postgres
   platform: postgres
  database:
   driverClassName: org.postgresql.Driver
liquibase:
   contexts: postgres